[package]
authors = ["jD91mZM2 <me@krake.one>"]
description = "xautolock rewrite in Rust, with a few extra features"
license-file = "LICENSE"
name = "xidlehook"
readme = "README.md"
repository = "https://github.com/jD91mZM2/xidlehook"
version = "0.6.1"

[dependencies]
clap = "2.32.0"
failure = "0.1.3"
mio = "0.6.16"

[dependencies.libpulse-sys]
optional = true
version = "1.3.4"

[dependencies.nix]
optional = true
version = "0.11.0"

[dependencies.x11]
features = ["xlib", "xss"]
version = "2.18.1"

[features]
default = ["pulse", "nix"]
pulse = ["libpulse-sys"]
